project:
  type: website
  output-dir: docs

website:
  title: "Qianmu Zheng - MUSA 5080 Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Weekly Notes 
        menu: 
          - href: weekly-notes/
            text: "All Notes"
          - href: weekly-notes/week-01-notes.qmd
            text: "Week 1 Notes"
          - href: weekly-notes/week-02-notes.qmd
            text: "Week 2 Notes"
      - text: "Labs"
        menu:
          - href: labs/lab1/week-03/policy_lab1.qmd
            text: "Lab 1"
      - text: "Assignments"
        menu:
          - href: assignments/assignment_1/assignment1.qmd
            text: "Assignment 1"
          - href: assignments/assignment_2/Qianmu_Zheng_assignment2.qmd
            text: "Assignment 2"
          - href: assignments/assignment_3/QianmuZheng_Appendix.qmd
            text: "Assignment 3"
            

format:
  html:
    theme: cosmo
    toc: true
    code-fold: true

execute:
  freeze: auto
